# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FinalProjectRender' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalProjectRender

	pod 'Firebase/Core'
	pod 'Firebase/Database'

  target 'FinalProjectRenderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalProjectRenderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
